name: Test and Build

on:
  push:
    branches:
    - main
    paths:
    - '**/*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #Setting up environment
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Setup
      uses: docker/setup-buildx-action@v2

    - name: Docker Credentials
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker tag
      id: version
      run: |
        VERSION=v$(date +"%Y%m%d%H%M%S")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # Build the Docker Image
    - name: Build Docker Image
      run: |
        docker build -t devsubham09/demo-vite:${{ env.VERSION }} .

    # Push the Docker Image
    - name: Push Docker Image
      run: |
        docker push devsubham09/demo-vite:${{ env.VERSION }}

    # UPdate the K8s Manifest Files
    - name: Update K8s Manifests
      run: |
        cat k8s/deployment.yaml
        sed -i "s|image: devsubham09/demo-vite:.*|image: devsubham09/demo-vite:${{ env.VERSION }}|g" k8s/deployment.yaml
        cat k8s/deployment.yaml

    # Update Github
    - name: Commit the changes
      run: |
        git config --global user.email "<>"
        git config --global user.name "GitHub Actions Bot"
        git checkout main
        git add k8s/deployment.yaml
        git commit -m "Update deploy.yaml with new image version - ${{ env.VERSION }}"
        git push origin main